resources:
  - kind: integration
    selector:
      query: 'true'
      logLimit: 300
    port:
      entity:
        mappings:
          identifier: ._id
          title: .identifier // .identifier + " - " + .title
          blueprint: '"portIntegration"'
          properties:
            installationAppType: .installationAppType
            version: .version
            installationType: .installationType
            status: .resyncState
            health: .__health
            lastResyncStart: .resyncState.lastResyncStart
            lastResyncEnd: .resyncState.lastResyncEnd
            nextResync: .resyncState.nextResync
            config: .config
            errorMessage: .__errorMessage
            successfulUpserts: .__successfulUpserts
            failedUpserts: .__failedUpserts
          
